readExistingProcess: false        # if set, will read the voteMetadata from the JSON instead of creating a new one
stopOnError: false

processInfoFilePath: "./cached-process-info.json"

ethNetworkId: "goerli"
vocdoniEnvironment: "dev"
tokenAddress: "0x2b7222146a805bba0dbb61869c4b3a03209dffba"
tokenBalanceMappingPosition: 2
privKeys:
- "0x...."
- "0x...."
- "0x...."
- "0x...."
- "0x...."

bootnodesUrlRw: "https://server/gateways.json"     # Bootnode used by default
dvoteGatewayUri:                                   # If set, overrides bootnodesUrlRw
dvoteGatewayPublicKey:                             # If set, overrides bootnodesUrlRw
web3Uri:                                           # If set, overrides bootnodesUrlRw
oracleUri: "https://signaling-oracle.dev.vocdoni.net/dvote"

encryptedVote: true
